name: Python Fake Test

on:
    pull_request:
      branches:
        - '*'  # This will run the build and test jobs for pull requests to all branches
  
  jobs:
    test-cpp:
        runs-on: ${{ matrix.os }}
        env: 
          ION_CONTRIB_PYTHON_VER: 3.2.2
          ARAVIS_PYTHON_VER: 0.8.31
          GENDC_PYTHON_VER: 0.3.3
        strategy:
            matrix:
              os: [ubuntu-22.04, windows-2019, windows-2022]
              tutorial_file_name: [tutorial0_get_device_info, tutorial0_set_device_info, tutorial1_display, tutorial2_control_camera, tutorial3_getting_frame_count, tutorial4_save_gendc_data, tutorial4_save_image_bin_data, tutorial5_parse_gendc_data, tutorial5_parse_image_bin_data]
    
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4.1.1
            with:
              submodules: recursive
